config/routes.rb
#encoding: UTF-8
Tareas::Application.routes.draw do
  resources :responsable_sessions, :only => [:new, :create, :destroy]
  
  resources :tareas do
    get :completa, on: :member
  end
  
  resources :responsables do
    get :autocompletar, on: :collection
  end
  
  # The priority is based upon order of :creation =>   # first created -> highest priority.

  # Sample of regular :route =>   #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named :route =>   #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with :options =>   #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-:resources =>   #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a :namespace =>   #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'tareas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # :Note => This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/tarea.rb
#encoding: UTF-8
class Tarea < ActiveRecord::Base
  #Relaciones  
  belongs_to :responsable
  

  #Validaciones  
  validates :nombre, :detalles, :autor, :presence => { 
  :message => 'no puede dejarlo en blanco' }
  validates :autor , :length => {:maximum => 15 }
  validates :fecha, :timeliness => {
   :type => :date, 
   :invalid_date_message => 'esta mal formada' }
  validates :fecha, :on => :create, :timeliness => {
  :type => :date,
  :on_or_after => :today,
  :on_or_after_message => 'debe ser para hoy o el futuro'
   }
  attr_accessor :auto_responsable
  before_validation :asignar_responsable
  
  #Métodos
  def to_s
    self.nombre
  end
  
  def asignar_responsable
    if self.auto_responsable.present?
      self.responsable = Responsable.find_by_nombre( self.auto_responsable )
    end
  end
  
 def self.recordar_vencimientos
    tareas = Tarea.where(
      ['fecha BETWEEN :hoy AND :futuro','responsable_id IS NOT NULL',
        'completa = :false'].join(' AND '), hoy: Date.today,
      futuro: 3.days.from_now.to_date, false: false
    )

    tareas.each do |tarea|
      TareasMailer.tarea_cerca_vencer(tarea).deliver
    end
  end

end

app/controllers/tareas_controller.rb
# encoding: UTF-8

class TareasController < ApplicationController
  before_filter :require_responsable
  
  proc { |controller| controller.request.xhr? ? false : 'application' }
  
  def index
    @tareas = Tarea.order('fecha').paginate(:page => params[:page], :per_page => 15)
    @tareas = @tareas.where(:autor => params[:autor]) if params[:autor]
    @tareas = @tareas.where(:responsable_id => params[:responsable_id]) if params[:responsable_id]
	
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tareas }
    end
  end
  
  # GET /tareas/1/completar
  # GET /tareas/1/completar.xml
  def completa
    @tarea = Tarea.find(params[:id])
    @tarea.update_attribute :completa, true
    @resp = current_responsable
    @tarea.update_attribute :autor, @resp.nombre
    
    
     if request.xhr?
      render :partial => 'tarea', :locals => {:tarea => @tarea}
    else
      respond_to do |format|
        format.html { redirect_to(tareas_url) }
        format.xml  { head :ok }
      end
     end
  end
  
  def show
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tarea }
    end
  end

  def new
    @tarea = Tarea.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tarea }
    end
  end

  def edit
    @tarea = Tarea.find(params[:id])
  end

  def create
    @tarea = Tarea.new(params[:tarea])

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to(@tarea, :notice => 'Tarea creada ^^') }
        format.xml  { render :xml => @tarea, :status => :created, :location => @tarea }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tarea.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      if @tarea.update_attributes(params[:tarea])
        format.html { redirect_to(@tarea, :notice => 'Tarea actualizada') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tarea.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @tarea = Tarea.find(params[:id])
    @tarea.destroy

    respond_to do |format|
      format.html { redirect_to(tareas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tareas_helper.rb
#encoding: UTF-8
module TareasHelper
end

app/views/tareas/_form.html.erb
<%= form_for(@tarea) do |f| %>
  <% if @tarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarea.errors.count, "error") %> La tarea no se pudo guardar:</h2>

      <ul>
      <% @tarea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre, placeholder: 'Nombre...' %>
  </div>
  <div class="field">
  <%= f.label :detalles %><br />
  <%= f.text_area :detalles, :rows => 5, placeholder: 'Detalles...' %>
 </div>
 <div class="field">
  <%= f.label :autor %><br />
  <%= f.text_field :autor, placeholder: 'Quien lo debería hacer...' %>
 </div>
 <div class="field">
  <%= f.label :fecha %><br />
  <%= f.date_select :fecha, :order => [:day, :month, :year] %>
 </div> 
 <div class="field" > 
   <%= f.label :auto_responsable, 'Responsable' %>
   <%= f.text_field :auto_responsable, value: @tarea.responsable.try(:nombre) %>
  <%# f.label :responsable_id %><br />
  <%#= f.hidden_field :responsable_id, :value => @current_responsable.id %>
  <%# f.select :responsable_id, Responsable.all.map {
  |r| [r.nombre, r.id]}, :include_blank => true  %>
 </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/tareas/_tarea.html.erb
 <tr>
    <td><%= link_to tarea.nombre, tarea %></td>
    <td><%= truncate tarea.detalles, :length => 25 %></td>
    <td><%= link_to tarea.autor, tareas_path(:autor => tarea.autor) %></td>
    <td><%= l tarea.fecha %></td> 
    <td><%= link_to tarea.responsable, 
            tareas_path(:responsable_id => tarea.responsable_id) %> </td>
    <td><%= tarea.completa ? 'Completa' : link_to('Completa?', completa_tarea_path(tarea), :remote => true, :class => 'tarea_completa', 'data-type' => 'html') %> </td>
  </tr>

app/views/tareas/edit.html.erb
<h1>Editar tarea</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tarea %> |
<%= link_to 'Volver', tareas_path %>

app/views/tareas/index.html.erb
<h1>Listado de tareas</h1>

<% if params[:responsable_id] %>
<h4>(Ordenado por: 
<%=  Responsable.find_by_id(params[:responsable_id]) %> )
<% end %> </h4>
<table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Autor</th>
    <th>Fecha</th>
    <th>Responsable</th>
    <th>Completar</th>
  </tr>

<%= render @tareas%>

</table>
<br />

<%= link_to 'Nueva Tarea', new_tarea_path %> |
<%= link_to 'Nuevo Responsable', new_responsable_path %> <br />
<%= will_paginate @tareas,
  :previous_label => '&laquo; Anterior',
  :next_label => 'Siguiente &raquo;'  %>

app/views/tareas/new.html.erb
<h1>Nueva Tarea</h1>

<%= render 'form' %>

<%= link_to 'Volver', tareas_path %>

app/views/tareas/show.html.erb
<p>
	<b>Nombre: </b>
	<%= @tarea.nombre %>
	<b>Detalles: </b>
	<%= @tarea.detalles %>
	<b>Autor: </b>
	<%= @tarea.autor %>
	<b>Fecha de creacion:</b>
	<%= @tarea.fecha %>
	<b>Responsable: </b>
	<%= @tarea.responsable %>
        <b>Completa?</b>
        <%= @tarea.completa ? 'Completa' : 'Pendiente' %>
        <br />
        <%= link_to 'Editar', edit_tarea_path(@tarea) %> |
        <%= link_to 'Eliminar', @tarea, :confirm => 'Seguro?!?!?!?', :method => :delete %>
</p>
 <br />
<%= link_to 'Tareas', tareas_path %> | 
<%= link_to 'Responsables', responsables_path %> 