config/routes.rb
#encoding: UTF-8
Tareas::Application.routes.draw do
  resources :responsable_sessions, :only => [:new, :create, :destroy]
  
  resources :tareas do
    get :completa, on: :member
  end
  
  resources :responsables do
    get :autocompletar, on: :collection
  end
  
  # The priority is based upon order of :creation =>   # first created -> highest priority.

  # Sample of regular :route =>   #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named :route =>   #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with :options =>   #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-:resources =>   #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a :namespace =>   #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'tareas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # :Note => This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/menus/_menu.html.erb
<div>
    <%= link_to Tarea.human_attribute_name(:tareas), tareas_path  %> | 
  <%= link_to Responsable.human_attribute_name(:responsables), responsables_path  %> | 
  
  
  
  <% if @current_responsable %>   
    <%= link_to @current_responsable,:controller => 'responsables', :action => 'edit', :id => @current_responsable  %> |
    <%= link_to "Salir", new_responsable_session_path, :method => :delete, :confirm => "Seguro?" %>
  <% else %>
    <%= link_to "Registrarse", new_responsable_path %> 
      <%  unless current_page?(:controller => 'responsable_sessions', :action => 'new') %>
      <%# unless responsable_session[:responsable] %>
      |  <%= link_to "Entrar", new_responsable_session_path  %>
      <% end %>
  <% end %>
      
</div>