config/routes.rb
#encoding: UTF-8
Tareas::Application.routes.draw do
  resources :responsable_sessions, :only => [:new, :create, :destroy]
  
  resources :tareas do
    get :completa, on: :member
  end
  
  resources :responsables do
    get :autocompletar, on: :collection
  end
  
  # The priority is based upon order of :creation =>   # first created -> highest priority.

  # Sample of regular :route =>   #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named :route =>   #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with :options =>   #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-:resources =>   #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a :namespace =>   #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'tareas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # :Note => This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/responsable.rb
#encoding: UTF-8
class Responsable < ActiveRecord::Base
	acts_as_authentic do |c|
    c.login_field = :email
  end
  	
	validates :nombre, :presence => { 
	:message => 'no puede dejarlo en blanco' }
	
	has_many :tareas
  scope :con_nombre, lambda { |nombre| where('LOWER(nombre) LIKE ?', "#{nombre}%".downcase) }

	def to_s 
		self.nombre
	end
  
  

end

app/controllers/responsables_controller.rb
#encoding: UTF-8
class ResponsablesController < ApplicationController
  before_filter :require_responsable, :except => [:new, :create]
 
  def index
    @responsables = Responsable.order('email').paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @responsables }
    end
  end

  def show
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @responsable }
    end
  end

  def new
    @responsable = Responsable.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @responsable }
    end
  end

  def edit
    @responsable = Responsable.find(params[:id])
  end

  def create
    @responsable = Responsable.new(params[:responsable])

    respond_to do |format|
      if @responsable.save
        ResponsableMailer.bienvenido(@responsable).deliver
        format.html { redirect_to(@responsable, :notice => 'Responsable creado =)') }
        format.xml  { render :xml => @responsable, :status => :created, :location => @responsable }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @responsable.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      if @responsable.update_attributes(params[:responsable])
        format.html { redirect_to(@responsable, :notice => 'Responsable actualizado =D.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @responsable.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @responsable = Responsable.find(params[:id])
    @responsable.destroy

    respond_to do |format|
      format.html { redirect_to(responsables_url) }
      format.xml  { head :ok }
    end
  end
  
  def autocompletar
    @responsables = Responsable.con_nombre(params[:term])

    respond_to do |format|
      format.js { render text: @responsables.map(&:to_s) }
    end
  end
 
end

app/helpers/responsables_helper.rb
#encoding: UTF-8
module ResponsablesHelper
end

app/views/responsables/_form.html.erb
<%= form_for(@responsable) do |f| %>
  <% if @responsable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsable.errors.count, "error") %> prohibited this responsable from being saved:</h2>

      <ul>
      <% @responsable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :email, 'Mail' %><br />
    <%= f.text_field :email, :size => 40 %>
  </div>
  <div>
   <%= f.label :password, 'Clave' %><br />
   <%= f.password_field :password, :size => 40 %>
  </div>
  <div>
   <%= f.label :password_confirmation, 'Respetir Clave' %><br />
   <%= f.password_field :password_confirmation, :size => 40 %>
  </div>
<% 3.times do %>
<br />
<% end %>
  <div class="actions">
    <%= f.submit 'Crear'%>
  </div>
<% end %>

app/views/responsables/edit.html.erb
<h1>Editing responsable</h1>

<%= render 'form' %>

<%= link_to 'Show', @responsable %> |
<%= link_to 'Back', responsables_path %>

app/views/responsables/index.html.erb
<h1>Responsables</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Mail</th>
  </tr>

<% @responsables.each do |responsable| %>
  <tr>
    <td><%= responsable.nombre %></td>
    <td><%= responsable.email %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Responsable', new_responsable_path %> <br />
<%= will_paginate @responsable,
  :previous_label => '&laquo; Anterior',
  :next_label => 'Siguiente &raquo;'  %>

app/views/responsables/new.html.erb
<h1>Nuevo Responsable</h1>

<%= render 'form' %>

app/views/responsables/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @responsable.nombre %>
</p>

<p>
  <b>Mail:</b>
  <%= @responsable.email %>
</p>
<p>
  <%= link_to 'Editar', edit_responsable_path(@responsable) %>
</p>


<br />
<%= link_to 'Tareas', tareas_path %> | 
<%= link_to 'Responsables', responsables_path %> 